version: 2
jobs:
  build:
    docker:
      - image: z0li/hugo-builder:latest
    working_directory: /src
    steps:
      - add_ssh_keys:
          fingerprints:
            - "52:79:b9:c8:44:7a:83:e8:ab:cd:3b:f5:39:2e:67:12"
      - checkout
      - run: git submodule update --init
      - run: hugo -v -s /src -d /src/public
      # - run:
      #     name: test the generated html files
      #     command: htmlproofer /src/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
      - deploy:
          name: push to master branch
          command: sh deploy.sh
